[package]
name = "untitled_lib"
version = "0.1.0"
authors = ["Jake <jakethecoder@outlook.com>"]
edition = "2018"
description = "SQL mapper"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]